### ISSUE TITLE
MVP - admin page

### ISSUE THREAD

**Issue by josue-rojas** [alexandriatech/behistun-inscription#69]
desire features
- [x] view and change user roles 
- [x] view and publish words
- [ ] view and publish definitions

Some rough sketches. 

## Frontend: 
The admin page should have 
- title 'Admin'
- tabs for different views
  - Users
    - Name
    - Role
    - Status!?!? Should be disabled in the beginning cause we are libertarian for now..... 
  - Words
    - Word
    - Author !? words don't really belong to anyone
    - Status (Publish or not) (button to toggle)
  - Defninitions
    -  Word
    - Definition
    - Tag
    - Author
    - Status: Publish or not (button that is to toggle)
 - Each tab should have a table with list

Table Requirements
https://ant.design/components/table/
we can use this to make it easier and later on develop our own. feel free to use their components aswell. 
UPDATE: 
We are using this instead https://table.react-component.now.sh/demo/fixed-columns-auto-height it is very similar and not dependent on a whole design system like ant and since ant seems to gone missing this is safer to use so we can replace just this later on. 

![Admin_Word_Table](https://user-images.githubusercontent.com/10749061/107725908-60921980-6cb5-11eb-8757-5ad070e80a93.jpg)
![Admin_Definition_Table](https://user-images.githubusercontent.com/10749061/107725910-612ab000-6cb5-11eb-935d-ea7408ddb46c.jpg)
![Admin_Page](https://user-images.githubusercontent.com/10749061/107725913-61c34680-6cb5-11eb-97b6-e8e1cacb7094.jpg)

## TODO:
- update task for backend

**Comment by PudparK** [comment]
- admin per dictionary
- accept new words (publish)
- a list of unpublished words for review
-

**Comment by josue-rojas** [comment]
with the new requirements this could probably be broken down,
maybe 
- table 
- tabs
- page views
